### ISSUE TITLE
Featured Project

### ISSUE THREAD

**Issue by knrscode** [unicef/innovation-fund#10]
![read more](https://cloud.githubusercontent.com/assets/11209271/17304428/8bcd4e34-57f3-11e6-9432-9d9092f90706.png)

Read More... links to the Featured Project Page

**Comment by knrscode** [comment]
![6](https://cloud.githubusercontent.com/assets/11209271/17304707/e64bc0ec-57f4-11e6-9bc5-4c531b2b99d4.png)
Align Graph legend and Height
![featured_graphs](https://cloud.githubusercontent.com/assets/11209271/17304605/78b2c954-57f4-11e6-9b5f-f65382d49856.png)

**Comment by mikefab** [comment]
1. "Read More... links to the Featured Project Page"
2. I don't think this is a critical to implement before launch.
3. It should be in a separate issue.
4. Left aligning the label
5. This seems difficult to fix as it's part of the polymer charts library.
6. Please place in a separate commit.
7. Graph placement:
   ![screen shot 2016-08-03 at 8 15 48 pm](https://cloud.githubusercontent.com/assets/42814/17386654/c256b3fa-59ba-11e6-8150-51c74013d7a8.png)

**Comment by mikefab** [comment]
Featured projects now have modals. Please see staging.
![screen shot 2016-08-21 at 7 03 54 pm](https://cloud.githubusercontent.com/assets/42814/17840342/1312785e-67d2-11e6-9832-60e190fcf63f.png)
