### ISSUE TITLE
Blog Posts

### ISSUE THREAD

**Issue by knrscode** [unicef/innovation-fund#11]
Blog Posts are blank need to comply with Original_blog stories_.png
![blog posts](https://cloud.githubusercontent.com/assets/11209271/17304818/833174c4-57f5-11e6-9f58-6a863ab74ca9.png)
![Uploading blogposts.png…]()

**Comment by knrscode** [comment]
Spacing between each blog post needs to comply with specs.

**Comment by knrscode** [comment]
Individual post Specs need to comply with attached screenshot
Current:
![blog posts_space](https://cloud.githubusercontent.com/assets/11209271/17451675/a0aac700-5b36-11e6-814b-27d9096870e6.png)

Required:
![image](https://cloud.githubusercontent.com/assets/11209271/17451709/e123beb8-5b36-11e6-92bd-addf397232e0.png)

**Comment by knrscode** [comment]
**Add Tags relevant to the Innovation fund.**

**Comment by mikefab** [comment]
Fixed blog card dimensions. Please view staging.
Also fixed but that crashed the site when unicefstories fails.
Still need to update tag when Comms gives it to me.

![screen shot 2016-08-21 at 10 01 15 pm](https://cloud.githubusercontent.com/assets/42814/17841840/d76c71ce-67ea-11e6-9b8e-eaf2b9e19616.png)
