### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by knrscode** [unicef/innovation-fund#12]
Unicef innovation 
![link_broken](https://cloud.githubusercontent.com/assets/11209271/17304942/1576f8cc-57f6-11e6-9e09-24bf5adfea08.png)
Link broken

**Comment by knrscode** [comment]
Image should link  to donors webpages.
![link to donors](https://cloud.githubusercontent.com/assets/11209271/17305029/87b13f60-57f6-11e6-96cf-a2d41275ab5c.png)

**Comment by knrscode** [comment]
![footer](https://cloud.githubusercontent.com/assets/11209271/17305230/72bdf444-57f7-11e6-8669-7126c80f1f77.png)
Share should link to relevant pages

**Comment by mikefab** [comment]
1. unicef.org link was fixed in content management spreadsheet.
2. Switched out sponsor.png with an image per sponsor.

**Comment by knrscode** [comment]
The links should open in a new tab/window
