### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by knrscode** [unicef/innovation-fund#13]
![modal](https://cloud.githubusercontent.com/assets/11209271/17305438/56f8924a-57f8-11e6-907d-1a21b1e49336.png)
Left align graph.
Evenly space graph within the card.
Add Title to the Graph

**Comment by knrscode** [comment]
IOGT [Graphs and Map] have to be placed one below the other and not adjacent
Need to add title

**Comment by mikefab** [comment]
- The cards are the same width.
- Still having difficulty balancing width and height of line chart. User must now scroll to see full chart.
- Still need to figure out iogt map label. Don't think it's critical, though.

![screen shot 2016-08-06 at 7 24 37 pm](https://cloud.githubusercontent.com/assets/42814/17459568/9b2d2216-5c0b-11e6-8497-83a8a43c05d9.png)
