### ISSUE TITLE
#6 - Responsiveness -Build for responsiveness using Iron Media Query.

### ISSUE THREAD

**Issue by knrscode** [unicef/innovation-fund#15]
![menu](https://cloud.githubusercontent.com/assets/11209271/17305806/5dd1c8fa-57fa-11e6-8d79-34daa11454c5.png)
On click of Menu list should hide the panel

**Comment by knrscode** [comment]
Change Highlight colour to UNICEF Blue, Font consistent with website, Icon replacement

**Comment by knrscode** [comment]
need to share new icons/design

**Comment by mikefab** [comment]
Done. Please view on staging-innovation.herokuapp.com.

**Comment by knrscode** [comment]
Build for responsiveness.
Suggest to use Iron Media Query. 
https://elements.polymer-project.org/elements/iron-media-query?view=demo:demo/index.html

Following components need to be responsive .

Blog posts, 
Charts
Project Cards

![responsive ui_graph-04](https://cloud.githubusercontent.com/assets/11209271/18768357/935ac7bc-80f2-11e6-8e0e-bae796a3ed84.png)
![responsive ui_graph-03](https://cloud.githubusercontent.com/assets/11209271/18768360/97a7dddc-80f2-11e6-803b-6d18a5e6a81c.png)
