### ISSUE TITLE
All Projects_Cards

### ISSUE THREAD

**Issue by knrscode** [unicef/innovation-fund#31]
@mikefab 

Required:

![cards](https://cloud.githubusercontent.com/assets/11209271/17707120/f6a99aae-63ac-11e6-8868-891e5ae84a21.png)

On Roll over- Card pops up and Icon appears. #

**Comment by mikefab** [comment]
Fixed. Please view on staging: staging-innovation.herokuapp.com

![screen shot 2016-08-20 at 10 39 36 pm](https://cloud.githubusercontent.com/assets/42814/17835015/2a43ccea-6727-11e6-916a-55669831b90b.png)
