### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by knrscode** [unicef/innovation-fund#9]
Change Bar graph font_color and Portfolio height to be aligned.
![1](https://cloud.githubusercontent.com/assets/11209271/17304273/d7173b62-57f2-11e6-8b5e-b2267e362447.png)

**Comment by mikefab** [comment]
Fixed but not yet deployed.
Simply changed portfolio_card_title class font-size from 22px to 20px

![screen shot 2016-08-03 at 7 45 02 pm](https://cloud.githubusercontent.com/assets/42814/17385777/dbc898ce-59b2-11e6-9bd6-3f47f2317acd.png)
